delete from studypoint;
delete from task;
delete from sp_class_studypoint_user;
delete from semester_period;
delete from sp_class;
delete from studypointuser_roles;
delete from studypoint_user;
delete from log_info;
delete from user_role;
